version: "3"

services:
  ## PHP-Apache service
  server:
    build:
      context: .
    container_name: beeater-webserver
    ports:
      - 80:80
    restart: always
    volumes:
      - ./source:/var/www/html
    env_file:
      - ./docker.env
    networks:
      - beeater

  ## Mariadb service
  database:
    image: mariadb:10.4.2
    container_name: beeater-database
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - beeater_data:/var/lib/mysql
    env_file:
      - ./docker.env
    networks:
      - beeater

  ## PhpMyAdmin
  myadmin:
    image: phpmyadmin/phpmyadmin:4.8.1
    container_name: beeater-phpmyadmin
    ports:
      - 8081:80
    restart: always
    env_file:
      - ./docker.env
    depends_on:
      - database
    networks:
      - beeater

networks:
  beeater:

volumes:
  beeater_data:
